// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-nwvnSFV6fLjAkY-egJXJ7fgYmTpfxhk',
    appId: '1:528910609537:web:4a24f40b2bbd06678ff180',
    messagingSenderId: '528910609537',
    projectId: 'tiktok-clone-jrsky723',
    authDomain: 'tiktok-clone-jrsky723.firebaseapp.com',
    storageBucket: 'tiktok-clone-jrsky723.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdjlPAMx-F9gVzgqs-4-jctnEhcgIBPuE',
    appId: '1:528910609537:android:cbccccb7d23b0c6a8ff180',
    messagingSenderId: '528910609537',
    projectId: 'tiktok-clone-jrsky723',
    storageBucket: 'tiktok-clone-jrsky723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnogaEW9ffKbSEOO8uZVojCKxsECecTJg',
    appId: '1:528910609537:ios:0856160a351b2c558ff180',
    messagingSenderId: '528910609537',
    projectId: 'tiktok-clone-jrsky723',
    storageBucket: 'tiktok-clone-jrsky723.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
